/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap' 

const Dtu = (props) => {

    const targetRef = useRef();

    useGSAP(()=>{
        gsap.to(targetRef.current.position, {
            z: targetRef.current.position.z+0.2,
            duration: 2,
            repeat: -1,
            yoyo: true,
            ease: 'power1.inOut',
        })
    })

  const { nodes, materials } = useGLTF('/models/dtu13.glb')
  return (
    <group {...props} dispose={null} 
    ref={targetRef}
    position={[-9, -14.5, 14.5]}
    rotation={[0, -0.2, 0]}
    >
       <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Sand.002']}
        position={[5.59, 13.825, -18.092]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Office Building']}
        position={[5.368, 14.511, -17.237]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[7.056, 14.614, -14.535]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.11}
      />
      <group position={[5.073, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.701}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.533, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.701}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil001.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot001.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1001.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.249, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.428}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil002.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.022, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot002.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1002.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.375, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.277}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil003.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot003.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1003.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.711, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.277}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil004.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot004.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1004.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[4.849, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.701}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil005.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot005.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1005.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.843, 14.055, -16.125]} rotation={[Math.PI, 0, Math.PI]} scale={0.701}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil006.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot006.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1006.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.318, 13.978, -13.9]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -13.604]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase001.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -13.339]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase002.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -13.099]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase003.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -20.717]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase004.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -21.332]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase005.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -21.961]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase006.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -22.612]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase007.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -23.271]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase008.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -23.875]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase009.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -24.533]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase010.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.318, 13.978, -25.199]} rotation={[Math.PI, 0, Math.PI]} scale={0.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase011.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[10.155, 13.814, -13.695]} rotation={[Math.PI, 0, Math.PI]} scale={0.483}>
        <mesh castShadow receiveShadow geometry={nodes.Trunk.geometry} material={materials.Bark} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[10.155, 13.814, -16.609]} rotation={[Math.PI, 0, Math.PI]} scale={0.841}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk001.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[10.155, 13.814, -19.74]} rotation={[Math.PI, 0, Math.PI]} scale={0.483}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk002.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[0.343, 13.814, -16.609]} rotation={[Math.PI, 0, Math.PI]} scale={0.841}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk003.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[0.343, 13.814, -20.769]} rotation={[Math.PI, 0, Math.PI]} scale={0.841}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk004.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[1.671, 13.814, -24.829]} rotation={[Math.PI, 0, Math.PI]} scale={0.841}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk005.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <group position={[9.353, 13.814, -24.091]} rotation={[Math.PI, 0, Math.PI]} scale={0.841}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trunk006.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_4.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_5.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_6.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_7.geometry}
          material={materials['Material.026']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.009']}
        position={[5.325, 15.601, -16.338]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.119}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['White thick strip fabric']}
        position={[5.325, 13.947, -17.206]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['White thick strip fabric']}
        position={[5.353, 13.904, -17.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['White thick strip fabric']}
        position={[5.325, 13.912, -13.475]}
        scale={[0.3, 0.636, 0.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['White thick strip fabric']}
        position={[5.325, 13.912, -23.077]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Concrete wall']}
        position={[5.33, 14.829, -17.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dtu.geometry}
        material={materials['Material.011']}
        position={[5.329, 15.096, -16.338]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.23, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dtu001.geometry}
        material={materials['Material.009']}
        position={[5.329, 14.618, -16.266]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.918, 1.05, 1.05]}
      />
      <group position={[6.798, 13.837, -14.582]} scale={0.192}>
        <group scale={2.529}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003.geometry}
            material={materials['Rzo_Shirt Dark']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_1.geometry}
            material={materials.Rzo_Shirt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_2.geometry}
            material={materials.Rzo_Skin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_3.geometry}
            material={materials.Rzo_Hair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_4.geometry}
            material={materials['Rzo_Bag Light']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_5.geometry}
            material={materials['Rzo_Bag Dark']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_6.geometry}
            material={materials.Rzo_Pants}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_7.geometry}
            material={materials.Rzo_Shoes_Shine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_8.geometry}
            material={materials['Rzo_Shoes Toe']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_9.geometry}
            material={materials.Rzo_Shoes_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_10.geometry}
            material={materials['Rzo_Bag Handle']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_11.geometry}
            material={materials.Rzo_Zipper}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Concrete wall']}
        position={[5.325, 15.725, -17.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['8K Brand new road']}
        position={[5.325, 13.84, -18.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.010']}
        position={[5.331, 15.159, -16.337]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04}
      />
    </group>
  )
}

useGLTF.preload('/models/dtu13.glb')

export default Dtu