/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const DtuNew =(props)=> {

    const targetRef = useRef();

    useGSAP(()=>{
        gsap.to(targetRef.current.position, {
            z: targetRef.current.position.z+0.4,
            duration: 2,
            repeat: -1,
            yoyo: true,
            ease: 'power1.inOut',
        })
    })

  const { nodes, materials } = useGLTF('/models/DtuNew.glb')
  return (
    <group {...props} dispose={null}
    ref={targetRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Dry soil']}
        position={[5.564, 13.978, -18.274]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.779, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Office Building']}
        position={[5.453, 14.331, -17.645]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[5.653, 14.102, -17.089]} rotation={[Math.PI, 0, Math.PI]} scale={0.351}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil006.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot006.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1006.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.511, 14.102, -17.089]} rotation={[Math.PI, 0, Math.PI]} scale={0.351}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil001.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot001.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1001.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.367, 14.102, -17.089]} rotation={[Math.PI, 0, Math.PI]} scale={0.351}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil002.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot002.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1002.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.22, 14.102, -17.089]} rotation={[Math.PI, 0, Math.PI]} scale={0.351}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.basil003.geometry}
          material={materials['Mat.']}
          position={[-0.002, 0.023, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot003.geometry}
          material={materials.pot}
          position={[0, 0.01, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pot_1003.geometry}
          material={materials.pot}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
      <group position={[5.428, 14.064, -15.976]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -15.828]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase001.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -15.696]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase002.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -15.576]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase003.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -19.385]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase004.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -19.692]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase005.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -20.007]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase006.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -20.332]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase007.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -20.662]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase008.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -20.964]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase009.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -21.293]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase010.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.428, 14.064, -21.626]} rotation={[Math.PI, 0, Math.PI]} scale={0.053}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vase011.geometry}
          material={materials['Flower Vase_Color']}
          scale={2.887}
        />
      </group>
      <group position={[5.758, 13.983, -22.41]} scale={4.036}>
        <group
          position={[0.407, 0, 2.055]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.077, 0.647, 0.554]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016.geometry}
            material={materials['Foot Path Sides']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016_1.geometry}
            material={materials['Foot Path']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016_2.geometry}
            material={materials['Main Road']}
          />
        </group>
      </group>
      <group position={[7.665, 13.983, -21.847]} scale={0.271}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere019.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere020.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere021.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere022.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere023.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere024.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere025.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
      </group>
      <group position={[7.665, 13.983, -18.473]} scale={0.457}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere008.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere009.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere010.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere011.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere012.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere013.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere014.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group position={[7.665, 13.983, -16.28]} scale={0.218}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere015.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere016.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere017.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere018.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere026.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere027.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere028.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group position={[7.665, 13.983, -15.118]} scale={0.43}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere029.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere030.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere031.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere032.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere033.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere034.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere035.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group position={[3.336, 13.983, -15.118]} rotation={[0, 0.959, 0]} scale={0.4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere036.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere037.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere038.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere039.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere040.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere041.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere042.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group position={[3.336, 13.983, -17.008]} scale={0.223}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere043.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere044.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere045.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere046.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere047.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere048.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere049.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group position={[3.336, 13.983, -18.549]} rotation={[0, 1.026, 0]} scale={0.321}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere050.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere051.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere052.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere053.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere054.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere055.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere056.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <group
        position={[3.336, 13.983, -20.604]}
        rotation={[Math.PI, -0.827, Math.PI]}
        scale={0.391}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials['Material.014']}
          position={[-0.003, 0.095, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere057.geometry}
          material={materials['Material.012']}
          position={[0.095, 3.985, -0.759]}
          rotation={[0, 0.646, 0]}
          scale={1.136}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere058.geometry}
          material={materials['Material.005']}
          position={[-0.926, 3.568, 0.662]}
          rotation={[0, -0.33, 0]}
          scale={[0.438, 0.984, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere059.geometry}
          material={materials['Material.003']}
          position={[1.164, 2.904, 0.782]}
          rotation={[Math.PI, 0.524, 0]}
          scale={[0.518, 0.378, 0.518]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere060.geometry}
          material={materials['Material.002']}
          position={[0.972, 3.135, 0.65]}
          rotation={[0, -1.326, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere061.geometry}
          material={materials['Material.015']}
          position={[0.783, 4.204, 0.557]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.636, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere062.geometry}
          material={materials['Material.004']}
          position={[-0.516, 4.155, 0.381]}
          rotation={[0, -0.33, 0]}
          scale={[0.871, 0.984, 0.871]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere063.geometry}
          material={materials['Material.012']}
          position={[-0.003, 4.695, 0.073]}
          rotation={[0, 0.646, 0]}
          scale={[1.136, 1.98, 1.136]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.009']}
        position={[5.432, 14.875, -17.195]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Concrete.004']}
        position={[5.432, 14.048, -17.629]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Concrete.004']}
        position={[5.432, 14.031, -15.764]}
        scale={[0.15, 0.318, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Concrete.004']}
        position={[5.432, 14.031, -20.565]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Concrete.004']}
        position={[5.434, 14.49, -17.64]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dtu.geometry}
        material={materials['Material.011']}
        position={[5.433, 14.623, -17.195]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.16, 0.115, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dtu001.geometry}
        material={materials['Material.009']}
        position={[5.433, 14.384, -17.16]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.459, 0.525, 0.525]}
      />
      <group position={[6.168, 13.993, -16.317]} scale={0.096}>
        <group position={[0, 0.005, 0]} scale={2.529}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003.geometry}
            material={materials['Rzo_Shirt Dark']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_1.geometry}
            material={materials.Rzo_Shirt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_2.geometry}
            material={materials.Rzo_Skin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_3.geometry}
            material={materials.Rzo_Hair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_4.geometry}
            material={materials['Rzo_Bag Light']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_5.geometry}
            material={materials['Rzo_Bag Dark']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_6.geometry}
            material={materials.Rzo_Pants}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_7.geometry}
            material={materials.Rzo_Shoes_Shine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_8.geometry}
            material={materials['Rzo_Shoes Toe']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_9.geometry}
            material={materials.Rzo_Shoes_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_10.geometry}
            material={materials['Rzo_Bag Handle']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled003_11.geometry}
            material={materials.Rzo_Zipper}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Concrete.004']}
        position={[5.432, 14.938, -17.696]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.010']}
        position={[5.434, 14.655, -17.195]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.02}
      />
    </group>
  )
}

useGLTF.preload('/models/DtuNew.glb')

export default DtuNew