
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const LaptopNew = (props)=> {

    const targetRef =useRef();
    const lidRef =useRef();

    const videoTexture = useVideoTexture('/assets/project1_final.mp4');
    videoTexture.center.set(0.5, 0.5);
    videoTexture.rotation = Math.PI / 2;

    useGSAP(()=>{
        gsap.to(targetRef.current.position, {
            y: targetRef.current.position.y+5,
            duration: 3,
           repeat: -1,
        yoyo: true,
        ease: 'power1.inOut',
    })

        gsap.to(lidRef.current.rotation, {
        x: lidRef.current.rotation.x - 1.8,
        duration: 3,
    })

    gsap.to(targetRef.current.rotation, {
        y: targetRef.current.rotation.y-6.2,
        duration: 2,
    })

    gsap.to(targetRef.current.position, {
        z: targetRef.current.position.z -8,
        duration: 2,
    })
    })
  const { nodes, materials } = useGLTF('/models/laptopDeci.glb')
  return (
    <group {...props} dispose={null} ref={targetRef} position={[2,-7,12]} rotation={[0,-0.5,0]}>
      <group scale={0.52}>
        <group position={[0, 0.017, -0.003]} rotation={[-0.016, 0, 0]} scale={0.274}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials.body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_2.geometry}
            material={materials.Dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_3.geometry}
            material={materials['Material.005']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.body}
          position={[0, 0.025, 0.149]}
          rotation={[0.001, 0, 0]}
          scale={0.121}
        />
        <group position={[0.006, 0.027, -0.093]} scale={0.259}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials.key}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials['key.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_3.geometry}
            material={materials['Material.006']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials['black.003']}
          position={[-0.393, 0.019, -0.222]}
          rotation={[0.001, 0, 0]}
          scale={[0.006, 0.004, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials['black.003']}
          position={[-0.393, 0.019, -0.183]}
          rotation={[0.001, 0, 0]}
          scale={[0.006, 0.004, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.body}
          position={[-0.4, 0.026, -0.213]}
          scale={[0.001, 0, 0.001]}
        />
        <group position={[0.321, 0.026, -0.213]} scale={[0.001, 0, 0.001]}>
          <mesh         
        //   speaker 2
        scale={[0.9, 1, 1]}
        position={[-0.4, 0.026, 0]}
        rotation={[0, 0, 0]}
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials.body}
          />
          <mesh 
        //                              speaker 2
        scale={[0.9, 1, 1]}
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials['black.001']}
          />
        </group>
        <group position={[0, 0.027, -0.28]} rotation={[1.6, 0, 0]} scale={0.259} ref={lidRef}>
          <group position={[0.001, -0.051, -0.002]} rotation={[1.572, 0, 0]} scale={1.06}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={materials.body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={materials['black.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_2.geometry}
              material={materials.screen
              }
            >
                <meshBasicMaterial map={videoTexture}
                />
                </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_3.geometry}
              material={materials.dark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_4.geometry}
              material={materials['glass.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_5.geometry}
              material={materials['Material.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_6.geometry}
              material={materials['Material.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_7.geometry}
              material={materials['glass.003']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_8.geometry}
              material={materials['Apple-logo']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={materials['Material.003']}
            position={[0.01, 0.064, -0.002]}
            rotation={[1.571, 0, 0]}
            scale={[0.044, 0.045, 0.049]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptopDeci.glb')

export default LaptopNew