/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const MacExport = (props)=> {

    const targetRef = useRef();
    const lidRef = useRef();
    
    useGSAP(()=>{
        gsap.to(lidRef.current.rotation, {
            x: lidRef.current.rotation.x -1.5,
        duration: 2,

    })    
    })
  const { nodes, materials } = useGLTF('/models/macExport.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.222, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.011, -0.059, -1.372]} scale={[2.173, 2.173, 1.087]}
          rotation={[1.5, 0, 0]} ref={lidRef}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials['Material.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials['Material.002']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Base}
            position={[0, -0.079, 0.828]}
            scale={[2.252, 0.083, 2.252]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Base}
            position={[2.264, -0.08, -1.409]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.058, 0.306, 0.038]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/macExport.glb')

export default MacExport;